# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-11 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MetaManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '\u8bbe\u5907', 'verbose_name_plural': '\u8bbe\u5907'},
        ),
        migrations.AlterModelOptions(
            name='signature',
            options={'verbose_name': '\u7b7e\u540d', 'verbose_name_plural': '\u7b7e\u540d'},
        ),
        migrations.AddField(
            model_name='signature',
            name='is_ota',
            field=models.BooleanField(default=False, verbose_name='OTA Ticket'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ecid',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='ECID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='generator',
            field=models.CharField(blank=True, max_length=32, verbose_name='\u968f\u673a\u6570\u79cd\u5b50'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hw_model',
            field=models.CharField(help_text='\u4f8b: n90ap', max_length=16, verbose_name='\u5e73\u53f0'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ios_build',
            field=models.CharField(blank=True, default='', help_text='\u4f8b: 15F5061e', max_length=16, verbose_name='iOS \u6784\u5efa\u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ios_version',
            field=models.CharField(help_text='\u4f8b: 11.4', max_length=16, verbose_name='iOS \u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='device',
            name='product_type',
            field=models.CharField(help_text='\u4f8b: iPhone10,3', max_length=16, verbose_name='\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='ap_nonce',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Blob \u968f\u673a\u6570'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='blob_build',
            field=models.CharField(blank=True, default='', help_text='\u4f8b: 15F5061e', max_length=16, verbose_name='Blob \u6784\u5efa\u53f7'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='blob_file',
            field=models.FileField(blank=True, help_text='\u9009\u62e9\u4e00\u4e2a Blob \u6587\u4ef6 (*.shsh2) \u4ee5\u4e0a\u4f20', max_length=255, null=True, upload_to='shsh2', verbose_name='Blob \u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='blob_version',
            field=models.CharField(help_text='\u4f8b: 11.4', max_length=16, verbose_name='Blob \u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MetaManagement.Device', verbose_name='\u8bbe\u5907'),
        ),
    ]
