# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaManagement', '0004_auto_20180711_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='signature',
            name='is_fetched',
            field=models.BooleanField(default=False, verbose_name='Blob \u5df2\u83b7\u53d6'),
        ),
    ]
